site_name: PyHub MCP Tools
site_url: https://mcp.pyhub.kr
site_description: Python library for automating applications through Anthropic MCP protocol
site_author: Your Name

repo_name: pyhub-kr/pyhub-mcptools
repo_url: https://github.com/pyhub-kr/pyhub-mcptools

copyright: Copyright &copy; 2025 파이썬사랑방 (<a href="mailto:me@pyhub.kr">me@pyhub.kr</a>)

theme:
  name: material
  custom_dir: overrides
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - content.code.copy

# https://squidfunk.github.io/mkdocs-material/customization/#additional-css
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - attr_list

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            show_root_heading: true
            show_object_full_path: false
            show_category_heading: true
            show_if_no_docstring: false
            heading_level: 2
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_caption: false
      caption_position: bottom
      background: white
      shadow: true
      manual: false

nav:
  - Home: index.md
  - 설치 방법:
      - setup/index.md
      - setup/windows/index.md
      - setup/macos/index.md
      - setup/cursor/index.md
      - setup/sse/index.md
      - setup/env/index.md
  - MCP 도구:
      - mcptools/index.md
      - mcptools/excel/index.md
      - mcptools/fs/index.md
      - 검색도구:
          - mcptools/search/index.md
          - mcptools/search/perplexity.md
      - mcptools/maps/index.md
  - 활용 레시피:
      - recipes/index.md
      - recipes/excel/index.md
#     - mcptools/hometax/index.md
#     - mcptools/shopping/index.md
  - release-notes.md

# - Getting Started:
#   - Installation: usage/installation.md
#   - Quickstart: usage/quickstart.md
# - User Guide:
#   - Excel Automation: usage/excel.md
#   - Browser Automation: usage/browser.md
